### ISSUE TITLE
打包后js css也太多了 三十多个

### ISSUE THREAD

**Issue by liuchihanxiang** [zce/dashboard#12]

**Comment by liuchihanxiang** [comment]
异步加载的模块打包划分的太细了吧

**Comment by zce** [comment]
具体有什么问题呢？数量又代表不了什么吧，除了核心的公用部分，功能部分本身就是按需加载的

业务代码本就应该分包~

当然，你也可以自己根据需要定制：

https://github.com/zce/dashboard/tree/vue/src/router

**Comment by zce** [comment]
ping @liuchihanxiang
