### ISSUE TITLE
请问 你这个鼠标图标是如何转换的呢

### ISSUE THREAD

**Issue by yun313350095** [zce/dashboard#14]
每一次页面更新的时候,

**Comment by zce** [comment]
https://github.com/zce/dashboard/blob/master/src/assets/styles/base/components.scss#L33-L35

**Comment by zce** [comment]
https://github.com/zce/dashboard/blob/master/src/plugins/nprogress.js

**Comment by zce** [comment]
ping @yun313350095

**Comment by yun313350095** [comment]
谢谢
