### ISSUE TITLE
The `layout.vue` of ui displaying bug

### ISSUE THREAD

**Issue by vanpipy** [zce/dashboard#25]
# Bug 
https://github.com/zce/dashboard/blob/60c352c257c14dca04793301fe1d4c4f50b127a5/src/views/layout.vue#L6

The element has attribute `class` equal to 'content' used as the container of the content from the routes, displaying as menus in the `aside` in the `layout.vue`. Follow this, no matter how many contents in the container, we just scroll it to take a look or more. But now, it's frozen cause the container has no declared height, the `overflow: auto` never did its work as wish.

**Comment by zce** [comment]
The `content` element supports overflow scrolling, but the `aside` element does not, because pop-up menus need to be implemented.

BTW, If you could offer a better way, PR welcome
