### ISSUE TITLE
多个层级的services怎样写呢？

### ISSUE THREAD

**Issue by rushairer** [zce/dashboard#30]
比如
DELETE /zoos/ID/animals/ID

如何写Resource？

谢谢

**Comment by zce** [comment]
这当然没有绝对的答案的

凑巧我认为需要更新一下 services，你可以参考一下

https://github.com/zce/dashboard/blob/a7a2c9f3607f65151649d5bd180bc89ae0cd7a95/src/services/resource.js#L5-L42

https://github.com/zce/dashboard/blob/a7a2c9f3607f65151649d5bd180bc89ae0cd7a95/src/services/posts.js#L5-L17

BTW, 与项目本身‘质量’无关的问题可以通过邮件与我沟通，没必要放到这里

**Comment by rushairer** [comment]
非常感谢
