### ISSUE TITLE
npm run build时报错

### ISSUE THREAD

**Issue by Garvolll** [zce/dashboard#6]
错误信息：Cannot find module 'xxxxxxxx\'node_modules\eslint-friendly-formatter''。
查看node_modules文件夹，里边eslint-friendly-formatter已经安装过了呀，不知道是什么原因，大师指点下

**Comment by zce** [comment]
可以通过执行 `npm ls` 查看依赖项是否安装正常

建议通过删除`node_modules`目录，重新执行 `npm install`，确保正常安装所有依赖

**Comment by zce** [comment]
ping @Garvolll
