### ISSUE TITLE
安装失败（见描述），有没有详细点的使用说明呢

### ISSUE THREAD

**Issue by johnson8212** [zce/dashboard#7]
第一步：# install dependencies
$ npm install
安装后，总是有些没有安装全，如下：
npm ERR! peer dep missing: node-sass@^4.0.0, required by sass-loader@6.0.3
npm ERR! missing: get-caller-file@^1.0.1, required by yargs@6.6.0
npm ERR! missing: os-locale@^1.4.0, required by yargs@6.6.0
npm ERR! missing: read-pkg-up@^1.0.1, required by yargs@6.6.0
npm ERR! missing: require-directory@^2.1.1, required by yargs@6.6.0
npm ERR! missing: require-main-filename@^1.0.1, required by yargs@6.6.0
npm ERR! missing: which-module@^1.0.0, required by yargs@6.6.0
npm ERR! missing: y18n@^3.2.1, required by yargs@6.6.0
npm ERR! missing: wrap-ansi@^2.0.0, required by cliui@3.2.0
第二步：
# serve with hot reload at http://localhost:2017
$ npm run dev

安装后，如下：

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":true}!./~/v
ue-loader/lib/style-compiler?{"id":"data-v-465f9692","scoped":false,"hasInlineCo
nfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue-loader/lib
/selector.js?type=styles&index=0!./app/views/demo/components/button.vue 4:14-404
 13:3-17:5 14:22-412
 @ ./app/views/demo/components/button.vue
 @ ./app/libraries/router/demo-routes.js
 @ ./app/libraries/router/main-routes.js
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

> Listening at http://localhost:2017/

这一步起到什么作用？之后的三个命令也出错
# build for production with minification
$ npm run build

# build for production and view the bundle analyzer report
$ npm run build --report

# build for production and deploy to gh-pages
$ npm run deploy

另外，dashboard  api-server 分别怎么安装及使用呢

**Comment by zce** [comment]
对于第一个问题，只有重新删除node_modules，再次执行安装，由于部分依赖镜像源在国外，所以不稳定，可以尝试科学上网。

其他的问题，请确保你具备该有的知识储备，不能直接把自身问题抛给我，希望理解。

Issues是讨论围绕这个项目自身的问题（可以理解为报bug）

**Comment by zce** [comment]
至于每个script的作用，已经在readme中注明
