### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by VVzhouxiaobai** [zce/dashboard#8]
<--- Last few GCs --->

  130284 ms: Mark-sweep 898.2 (996.1) -> 898.0 (996.1) MB, 208.3 / 0.0 ms [alloc
ation failure] [GC in old space requested].
  130487 ms: Mark-sweep 898.0 (996.1) -> 898.0 (996.1) MB, 202.9 / 0.0 ms [alloc
ation failure] [GC in old space requested].
  130722 ms: Mark-sweep 898.0 (996.1) -> 897.8 (960.1) MB, 235.6 / 0.0 ms [last
resort gc].
  130971 ms: Mark-sweep 897.8 (960.1) -> 897.8 (947.1) MB, 248.5 / 0.0 ms [last
resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0397B815 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=0B8E0FA5] (this=039081D9 <u
ndefined>,w=0C763BDD <JS Array[2227]>,x=2227,N=03908201 <true>,J=03908229 <Strin
g[0]: >,I=0396DD61 <JS Function ConvertToString (SharedFunctionInfo 039365F5)>)
    2: Join(aka Join) [native array.js:180] [pc=0F1C8342] (this=039081D9 <undefi
ned>,w=0C763BDD <JS Array[2227]>,x=2227,J=03908229 <String[0]: >,I=0396DD61 <JS
Fun...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memo
ry

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js
" "run" "dev"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pdnms-front@2.0.0 dev: `node --max_old_space_size=1024 build/dev-server
.js`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pdnms-front@2.0.0 dev script 'node --max_old_space_size=1
024 build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pdnms-front package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=1024 build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pdnms-front
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pdnms-front
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\project\pdnms-front\npm-debug.log

**Comment by zce** [comment]
duplicated #9
